#app:
#  dataSource:
#    postgres:
#      port: 5432
#      username: postgres
#      password: password
#      host: localhost
#      databaseName: artexpapi
#        jdbc-url: jdbc:postgresql://${app.dataSource.postgres.host}:${app.dataSource.postgres.port}/${app.dataSource.postgres.databaseName}}
